### ISSUE TITLE
[Submission] Golem JS Preview Program

### ISSUE THREAD

**Issue by mohammed-a-hamdy** [golemfactory/golem-js-preview-program#10]
# Golem JS Preview Program Submission by mohammed-a-hamdy

Thank you for your Golem JS Preview Program Submission!

Please make sure the feedback form in a Markdown file is filled for each of the tasks you’d like to submit!
Also, please make sure you've read the terms and conditions for this competition available here - 

## Legal Info

In order to receive the award, we need a minimum info about you for legal reasons:

- Email: heroboy107@gmail.com
- Country of origin: Egypt

## Preferred reward currency

There are two currencies you can receive a reward in - USD and GLM. Since GLM is our cryptocurrency, we provide an additional **10% bonus to all rewards paid in GLMs!**.

Choose the preferred currency by checking (with `x`) one of the boxes below:

- [x] USD
- [ ] GLM (+10% bonus)

Please note that if you already have an accepted assignment from any of the freelance websites (e.g. fiverr.com, freelancer.com, upwork.com), you need to choose a reward in USD.

## Repository link

(https://github.com/mohammed-a-hamdy/golem-js-preview-program)

## Submitted Tasks

Please check (with `x`) the boxes below with the tasks you'd like to submit:

- [ ] Text2Speech
- [ ] Code Sandbox
- [ ] Parallel File Conversion
- [ ] Text2Speech Server
- [x] Best Provider Selection

## How did you find out about Golem JS Preview Program? Please check (with `x`) the correct box below:

- [ ] fiverr.com 
- [ ] freelancer.com
- [x] upwork.com
- [ ] Digital Campaign (e.g. Reddit)
- [ ] Golem Network profiles
- [ ] Message on LinkedIn
- [ ] Other: [please answer here]

## How was your experience with Golem JS Preview Program so far?

It's epic, I really enjoyed tinkering with the API and exploring it's various options in JS, i was a little anxious at first since the documentation was lacking but going forward it was fun after discovering what everything do and how the flow work

## Were the tasks easy to understand and did you enjoy solving them?

Yes it was very easy to understand, I enjoyed the last half of it as I was unable to figure out the API at first 

## How was your experience with a new Golem JS API?

It's like a maze, proper guidance is required and a lot of examples and documentation to make the best use of it. 
There were a lot of unexplainable errors using the core API, and I didn't figure out what each means nor I found it in the docs.

## Do you have any general feedback about Golem? Is there something we could improve from your perspective?

Yes, some specific configurations and customization are required like setting a max and min offer amount, finding specific providers, like recurring providers and min time required to achieve the task 

## And that's it - thank you for your submission!

Our team will review and evaluate your feedback, then reward you with GLM reward for your future projects!

**Comment by VanDavv** [comment]
Hi @mohammed-a-hamdy, 

Thanks a ton for your submission! I have one question about your suggestion:

> Yes, some specific configurations and customization are required like setting a max and min offer amount, finding specific providers, like recurring providers and min time required to achieve the task

Could you provide more context on how you'd like these features to look like? These are 3 separate features and I'd like understand your idea on them to be able to share my perspective 🙂

**Comment by mohammed-a-hamdy** [comment]
> 

Allow me to elaborate on some specific experiences I have encountered:

1. Maximum and Minimum Offer Amounts:
When faced with a demanding task, I occasionally encounter situations where my available funds are inadequate or I prefer to limit my expenditure. In such cases, it would be advantageous for the API to incorporate a feature that allows me to specify both a minimum and maximum amount in GLM that I am willing to spend.

2. Selection of Specific Providers:
During the execution of "Task 5," one of the challenges I faced was identifying the most capable providers capable of completing a given task. Subsequently, it became necessary to choose one of these providers to accomplish an even more intricate objective. Presently, the solution to this challenge involves repeatedly executing the algorithm and searching for offers from providers until one of them corresponds to a provider on my designated list. This process is both time-consuming and resource-intensive. It would be advantageous to have a streamlined function within the core API that accepts an array of preferred providers, enabling the algorithm to selectively pick from this list. Alternatively, if applicable, the ability to cache a direct access to these providers within my executer script would also be highly beneficial.

3. Minimum Required Time:
Although I did not find a direct answer within the core API, it is worth discussing the possibility of determining the estimated execution time for a task prior to its initiation. For instance, let's assume that Task A typically requires 5 to 10 seconds to complete. Having access to this information beforehand would enable me to assess the feasibility and value of executing the task on a particular provider.

These experiences serve as valuable insights, and it is possible that some of the aforementioned concerns are already being addressed by your development team. Nevertheless, I believe it is worthwhile to mention them once again.

**Comment by VanDavv** [comment]
Thanks a lot for the update! I'll discuss these with the team, but I think e.g. selection of providers and spendings control will be addressed in the upcoming releases of the JS API.

With this, I'm happy to accept the submission, thanks again!
