### ISSUE TITLE
[Submission] Golem JS Preview Program

### ISSUE THREAD

**Issue by lightify97** [golemfactory/golem-js-preview-program#11]
# Golem JS Preview Program Submission by lightify97

Thank you for your Golem JS Preview Program Submission!

Please make sure the feedback form in a Markdown file is filled for each of the tasks you’d like to submit!
Also, please make sure you've read the terms and conditions for this competition available here - 

## Legal Info

In order to receive the award, we need a minimum info about you for legal reasons:

- Email: ramzanm461@gmail.com
- Country of origin: Pakistan

## Preferred reward currency

There are two currencies you can receive a reward in - USD and GLM. Since GLM is our cryptocurrency, we provide an additional **10% bonus to all rewards paid in GLMs!**.

Choose the preferred currency by checking (with `x`) one of the boxes below:

- [x] USD
- [ ] GLM (+10% bonus)

Please note that if you already have an accepted assignment from any of the freelance websites (e.g. fiverr.com, freelancer.com, upwork.com), you need to choose a reward in USD.

## Repository link

https://github.com/lightify97/golem-js-preview-program/tree/master/tasks/1-text-2-speech

## Submitted Tasks

Please check (with `x`) the boxes below with the tasks you'd like to submit:

- [x] Text2Speech
- [ ] Code Sandbox
- [ ] Parallel File Conversion
- [ ] Text2Speech Server
- [ ] Best Provider Selection

## How did you find out about Golem JS Preview Program? Please check (with `x`) the correct box below:

- [ ] fiverr.com 
- [ ] freelancer.com
- [x] upwork.com
- [ ] Digital Campaign (e.g. Reddit)
- [ ] Golem Network profiles
- [ ] Message on LinkedIn
- [ ] Other: [please answer here]

## How was your experience with Golem JS Preview Program so far?

Working with Golem was a very interesting experience. It's actually my first time working with a Web3 project. Enjoyed every bit of it.

## Were the tasks easy to understand and did you enjoy solving them?

Yes, the tasks were easy, and I had no major difficulty solving them. I did enjoy solving them but If these were a bit challenging it'd be more rewarding.

## How was your experience with the new Golem JS API?

The API is great and very well written. Hoping to build more great things with it in near future.

## Do you have any general feedback about Golem? Is there something we could improve from your perspective?

I've mentioned in detail in the Feedback form. Please have a look there.

## And that's it - thank you for your submission!

Our team will review and evaluate your feedback, then reward you with GLM reward for your future projects!

**Comment by VanDavv** [comment]
Thanks a lot @lightify97, no questions this time and I'm happy to accept your feedback. Also, it's great to see you've used a different text-2-speech tool than was initially proposed

**Comment by lightify97** [comment]
Just wanted to test something new. Now I'm confident that Golem can run anything we throw at it.
