### ISSUE TITLE
[Submission] Golem JS Preview Program

### ISSUE THREAD

**Issue by gopalgoyal2002** [golemfactory/golem-js-preview-program#12]
# Golem JS Preview Program Submission by Gopal Goyal

Thank you for your Golem JS Preview Program Submission!

Please make sure the feedback form in a Markdown file is filled for each of the tasks you’d like to submit!
Also, please make sure you've read the terms and conditions for this competition available here - 

## Legal Info

In order to receive the award, we need a minimum info about you for legal reasons:

- Email: gopalgoyal612002@gmail.com
- Country of origin: India

## Preferred reward currency

There are two currencies you can receive a reward in - USD and GLM. Since GLM is our cryptocurrency, we provide an additional **10% bonus to all rewards paid in GLMs!**.

Choose the preferred currency by checking (with `x`) one of the boxes below:

- [x] USD
- [ ] GLM (+10% bonus)

Please note that if you already have an accepted assignment from any of the freelance websites (e.g. fiverr.com, freelancer.com, upwork.com), you need to choose a reward in USD.

## Repository link

https://github.com/gopalgoyal2002/golem-js-preview-program

## Submitted Tasks

Please check (with `x`) the boxes below with the tasks you'd like to submit:

- [ ] Text2Speech
- [ ] Code Sandbox
- [ ] Parallel File Conversion
- [x] Text2Speech Server
- [ ] Best Provider Selection

## How did you find out about Golem JS Preview Program? Please check (with `x`) the correct box below:

- [ ] fiverr.com 
- [ ] freelancer.com
- [x] upwork.com
- [ ] Digital Campaign (e.g. Reddit)
- [ ] Golem Network profiles
- [ ] Message on LinkedIn
- [ ] Other: [please answer here]

## How was your experience with Golem JS Preview Program so far?

My experience was good with the Golem JS preview program. It was a unique experience to do that type of task for me.

## Were the tasks easy to understand and did you enjoy solving them?

Yes, tasks were easy to understand and because of documentation, they become easier. I enjoyed solving them.

## How was your experience with a new Golem JS API? 

The experience was good with Golem JS API they are user-friendly and APIs are very simple to understand and implementation is also simple.

## Do you have any general feedback about Golem? Is there something we could improve from your perspective?

Golem's work is awesome and hope to work in the future also. I have written more things in the feedback form.

## And that's it - thank you for your submission!

Our team will review and evaluate your feedback, then reward you with GLM reward for your future projects!

**Comment by VanDavv** [comment]
Thanks a lot for your submission @gopalgoyal2002 and I'm very happy you enjoyed the task. Hope to see you around on our Discord and you can consider the submission accepted 😄
