### ISSUE TITLE
[Submission] Golem JS Preview Program

### ISSUE THREAD

**Issue by mohammed-a-hamdy** [golemfactory/golem-js-preview-program#13]
# Golem JS Preview Program Submission by <your_username>

Thank you for your Golem JS Preview Program Submission!

Please make sure the feedback form in a Markdown file is filled for each of the tasks you’d like to submit!
Also, please make sure you've read the terms and conditions for this competition available here - 

## Legal Info

In order to receive the award, we need a minimum info about you for legal reasons:

- Email: heroboy107@gmail.com
- Country of origin: Egypt

## Preferred reward currency

There are two currencies you can receive a reward in - USD and GLM. Since GLM is our cryptocurrency, we provide an additional **10% bonus to all rewards paid in GLMs!**.

Choose the preferred currency by checking (with `x`) one of the boxes below:

- [x] USD
- [ ] GLM (+10% bonus)

Please note that if you already have an accepted assignment from any of the freelance websites (e.g. fiverr.com, freelancer.com, upwork.com), you need to choose a reward in USD.

## Repository link

(https://github.com/mohammed-a-hamdy/golem-js-preview-program/blob/master/tasks/3-parallel-file-conversion/FEEDBACK.md)

## Submitted Tasks

Please check (with `x`) the boxes below with the tasks you'd like to submit:

- [ ] Text2Speech
- [ ] Code Sandbox
- [x] Parallel File Conversion
- [ ] Text2Speech Server
- [x] Best Provider Selection

## How did you find out about Golem JS Preview Program? Please check (with `x`) the correct box below:

- [ ] fiverr.com 
- [ ] freelancer.com
- [x] upwork.com
- [ ] Digital Campaign (e.g. Reddit)
- [ ] Golem Network profiles
- [ ] Message on LinkedIn
- [ ] Other: [please answer here]

## How was your experience with Golem JS Preview Program so far?

I cannot emphasize enough how impressed I am with the tremendous exposure and functionality that I have been fortunate enough to experience. It has truly exceeded my expectations and completely blown my mind. Coming from an industry that frequently grapples with limited resources, witnessing such a solution has left me in awe.

The potential impact that this solution could have on numerous fields is simply remarkable. If this solution were to be made commercially available, its effects would be far-reaching and transformative. It has the potential to revolutionize industries that have long struggled with insufficient resources and open up new possibilities for innovation and growth.

## Were the tasks easy to understand and did you enjoy solving them?

Without a doubt, the ease of understanding the functionalities provided was one of the standout features for me. It was a pleasant surprise to find that most of the functionalities were intuitive and straightforward to grasp. Despite encountering challenges with the lack of proper documentation, I thoroughly enjoyed exploring and utilizing these features.

While proper documentation is undeniably important for comprehensive understanding and smooth implementation, it is a testament to the user-friendliness of the functionalities that I was able to navigate and make the most of them. It speaks volumes about the thoughtfulness and design behind the system, which made it accessible and enjoyable to work with.

## How was your experience with a new Golem JS API?

Although I didn't have the opportunity to test the previous version, I must say that the new version is truly impressive. It offers a seamless experience with simplified coding and straightforward requirements, making it a joy to work with.

## Do you have any general feedback about Golem? Is there something we could improve from your perspective?
Regarding the web solution challenge, I would have appreciated a direct method to access the API rather than implementing it as a script within the web page. It would be great to have something like `fetch('golem-requester', with proper requirements).then(res)`—a simple approach that can be used directly within an HTML file.

## And that's it - thank you for your submission!

Our team will review and evaluate your feedback, then reward you with GLM reward for your future projects!

**Comment by VanDavv** [comment]
Thanks a lot for your feedback @mohammed-a-hamdy! We are working on preparing tutorials covering specific functionality sets, so I'll be more than happy to share them with you once they are available - so if you'd wish to stay around with us a bit longer, feel free to reach out on Discord.

And you can consider this submission accepted, thanks again for your excellent feedback!
