### ISSUE TITLE
[Submission] Golem JS Preview Program

### ISSUE THREAD

**Issue by OjusWiZard** [golemfactory/golem-js-preview-program#14]
# Golem JS Preview Program Submission by @OjusWiZard

Thank you for your Golem JS Preview Program Submission!

Please make sure the feedback form in a Markdown file is filled for each of the tasks you’d like to submit!
Also, please make sure you've read the terms and conditions for this competition available here - 

## Legal Info

In order to receive the award, we need a minimum info about you for legal reasons:

- Email: ojuswimail@gmail.com
- Country of origin: India

## Preferred reward currency

There are two currencies you can receive a reward in - USD and GLM. Since GLM is our cryptocurrency, we provide an additional **10% bonus to all rewards paid in GLMs!**.

Choose the preferred currency by checking (with `x`) one of the boxes below:

- [x] USD
- [ ] GLM (+10% bonus)

Please note that if you already have an accepted assignment from any of the freelance websites (e.g. fiverr.com, freelancer.com, upwork.com), you need to choose a reward in USD.

## Repository link

https://github.com/OjusWiZard/golem-js-preview-program

## Submitted Tasks

Please check (with `x`) the boxes below with the tasks you'd like to submit:

- [ ] Text2Speech
- [ ] Code Sandbox
- [ ] Parallel File Conversion
- [ ] Text2Speech Server
- [x] Best Provider Selection

## How did you find out about Golem JS Preview Program? Please check (with `x`) the correct box below:

- [ ] fiverr.com 
- [ ] freelancer.com
- [x] upwork.com
- [ ] Digital Campaign (e.g. Reddit)
- [ ] Golem Network profiles
- [ ] Message on LinkedIn
- [ ] Other: [please answer here]

## How was your experience with Golem JS Preview Program so far?

As a newbie to Golem, the experience was challenging but I enjoyed the whole process as I shattered through the blockers one by one. This is the second task I submitted after task 1, so it was definitely more challenging. But, I was prepared for it :D

## Were the tasks easy to understand and did you enjoy solving them?

Yes, the tasks were easy to understand. I enjoyed it a lot but would have enjoyed it more with typescript.

## How was your experience with a new Golem JS API?

The API seems comfortable to work with. The real challenge was to learn it. Once I knew how to do something, it became easy to use.

## Do you have any general feedback about Golem? Is there something we could improve from your perspective?

Golem's concept is very impressive to me. I see it as the decentralized AWS in the future.

## And that's it - thank you for your submission!

Our team will review and evaluate your feedback, then reward you with GLM reward for your future projects!

**Comment by VanDavv** [comment]
Thanks @OjusWiZard for another submission!

And I'm really sorry for not including TypeScript in the descriptions of the task - as yes, you could use TypeScript, and it's up to developers whether to use plain JS or with types. This is something I'll take a look at and tweak. 

The feedback overall is great, will definitely address some of these points with the team. You can consider this submission accepted, thanks again!
