### ISSUE TITLE
[Submission] Golem JS Preview Program

### ISSUE THREAD

**Issue by piotrgerke** [golemfactory/golem-js-preview-program#2]
# Golem JS Preview Program Submission by <your_username>

Thank you for your Golem JS Preview Program Submission!

Please make sure the feedback form in a Markdown file is filled for each of the tasks you’d like to submit!
Also, please make sure you've read the terms and conditions for this competition available here - 

To receive the award, you will also need to fill out our KYC for legal reasons.

## Repository link

[Please provide here a link to your fork of this repository, containing your implementation and feedback forms]

## Submitted Tasks

Please check (with `x`) the boxes below with the tasks you'd like to submit:

- [ ] Yagna Setup
- [ ] Text2Speech
- [ ] Code Sandbox
- [ ] Parallel File Conversion
- [ ] Text2Speech Server
- [ ] Best Provider Selection

## How was your experience with Golem JS Preview Program so far?

[please answer here]

## Were the tasks easy to understand and did you enjoy solving them?

[please answer here]

## How was your experience with a new Golem JS API?

[please answer here]

## Do you have any general feedback about Golem? Is there something we could improve from your perspective?

[please answer here]

## And that's it - thank you for your submission!

Our team will review and evaluate your feedback, then reward you with GLM reward for your future projects!

**Comment by VanDavv** [comment]
This is a test submission, closing
