### ISSUE TITLE
[Submission] Golem JS Preview Program

### ISSUE THREAD

**Issue by WalterBanda** [golemfactory/golem-js-preview-program#4]
# Golem JS Preview Program Submission by @WalterBanda

Thank you for your Golem JS Preview Program Submission!

Please make sure the feedback form in a Markdown file is filled for each of the tasks you’d like to submit!
Also, please make sure you've read the terms and conditions for this competition available here - 

## Legal Info

In order to receive the award, we need a minimum info about you for legal reasons:

- Email: walterkaimurima@gmail.com
- Country of origin: Kenya

## Preferred reward currency

There are two currencies you can receive a reward in - USD and GLM. Since GLM is our cryptocurrency, we provide an additional **10% bonus to all rewards paid in GLMs!**.

Choose the preferred currency by checking (with `x`) one of the boxes below:

- [x] USD
- [ ] GLM (+10% bonus)

Please note that if you already have an accepted assignment from any of the freelance websites (e.g. fiverr.com, freelancer.com, upwork.com), you need to choose a reward in USD.

## Repository link

https://github.com/WalterBanda/golem-js-preview-program

## Submitted Tasks

Please check (with `x`) the boxes below with the tasks you'd like to submit:

- [ ] Text2Speech
- [x] Code Sandbox
- [ ] Parallel File Conversion
- [ ] Text2Speech Server
- [ ] Best Provider Selection

## How did you find out about Golem JS Preview Program? Please check (with `x`) the correct box below:

- [ ] fiverr.com 
- [ ] freelancer.com
- [x] upwork.com
- [ ] Digital Campaign (e.g. Reddit)
- [ ] Golem Network profiles
- [ ] Message on LinkedIn
- [ ] Other: [please answer here]

## How was your experience with Golem JS Preview Program so far?

It was great, I learned a lot about the practical applications of blockchain other can crypto currencies and nfts. I was especially interested in how Golem uses blockchain as an execution environment. The developer docs are easy to understand and follow through but it is easy to get confused with the different docs sites available.

## Were the tasks easy to understand and did you enjoy solving them?

Yeah, It was a great experience working on it, looking at new spins, and making the features a reality. Though with the API in the early stages with a few rough edges, I would say it was great. The instructions were very easy to understand and follow through.

## How was your experience with a new Golem JS API?

The Golem JS API is great and working with it is a great candidate for server-side rendered web apps or client web apps with server actions for task execution. The API works great for web apps that have access to a server ie the scripts run on nodejs runtime not the browser runtime which is due to the following bugs,
| Bug | Screenshot | Log files |
|--------|--------|--------|
| bug in Account constructor where it fails to pass yagnaOptions down resulting in searching of app key in process.env and when a polyfill is provided the check fails. | ![Screenshot from 2023-05-16 01-37-17](https://github.com/golemfactory/golem-js-preview-program/assets/56268243/897a20af-141f-4e8e-8d26-2ba787963108) | [localhost-app_key.log](https://github.com/golemfactory/golem-js-preview-program/files/11482645/localhost-app_key.log)|
| Gvmkit-build: Docker Exception is raised whenever there is a network activity for docker during build |![Screenshot from 2023-05-16 02-44-07](https://github.com/golemfactory/golem-js-preview-program/assets/56268243/5aa0d6d1-eb8b-40ff-9b5d-fe92eed1a78f) | [gvmkit-build.log](https://github.com/golemfactory/golem-js-preview-program/files/11482661/gvmkit-build.log) |

For my recommendation, the [TaskExecutor] API is a great choice, it is relatively simple and straightforward to use but the browser API is more flexible.

## Do you have any general feedback about Golem? Is there something we could improve from your perspective?

Great technology that brings a new perspective and view to the use of blockchain especially when blockchain is mostly known for cryptocurrency. With the use of docker containers as an execution point, it can create a scalable platform for deploying Dapps

## And that's it - thank you for your submission!

Our team will review and evaluate your feedback, then reward you with GLM reward for your future projects!

**Comment by VanDavv** [comment]
Hi Walter

Thank you for your submission! And great catch with yagnaOptions, already forwarded it to the team and created an internal issue. 
We're also in a process of migrating the old docs to the new system, so I hope that as more and more articles are migrated, the less confusion will be there. As a temporary solution, I've also added an issue to include banners on migrated pages, pointing to new docs.

Submission is accepted, thanks again for your feedback!

**Comment by VanDavv** [comment]
Hey @WalterBanda,

We just released a new version of the `gvmkit-build`, `0.2.9`, available here - https://pypi.org/project/gvmkit-build/
It should contain the fix for the `chunked` issue.

Thanks again for your submission!
