### ISSUE TITLE
 [Submission] Golem JS Preview Program

### ISSUE THREAD

**Issue by tewodrosGirmaA** [golemfactory/golem-js-preview-program#6]
# Golem JS Preview Program Submission by <@tewodrosGirmaA>

Thank you for your Golem JS Preview Program Submission!

Please make sure the feedback form in a Markdown file is filled for each of the tasks you’d like to submit!
Also, please make sure you've read the terms and conditions for this competition available here - 

## Legal Info

In order to receive the award, we need a minimum info about you for legal reasons:

- Email: [tedigirmaabebe@gmail.com(GitHub) and surashblues234@gmail.com(Upwork)]
- Country of origin: [Ethiopia]

## Preferred reward currency

There are two currencies you can receive a reward in - USD and GLM. Since GLM is our cryptocurrency, we provide an additional **10% bonus to all rewards paid in GLMs!**.

Choose the preferred currency by checking (with `x`) one of the boxes below:

- [x] USD
- [ ] GLM (+10% bonus)

Please note that if you already have an accepted assignment from any of the freelance websites (e.g. fiverr.com, freelancer.com, upwork.com), you need to choose a reward in USD.

## Repository link

https://github.com/tewodrosGirmaA/golem-js-preview-program

## Submitted Tasks

Please check (with `x`) the boxes below with the tasks you'd like to submit:

- [ ] Text2Speech
- [ ] Code Sandbox
- [x] Parallel File Conversion
- [ ] Text2Speech Server
- [ ] Best Provider Selection

## How did you find out about Golem JS Preview Program? Please check (with `x`) the correct box below:

- [ ] fiverr.com 
- [ ] freelancer.com
- [x] upwork.com
- [ ] Digital Campaign (e.g. Reddit)
- [ ] Golem Network profiles
- [ ] Message on LinkedIn
- [ ] Other: [please answer here]

## How was your experience with Golem JS Preview Program so far?

Overall, my experience with the Golem JS Preview Program has been positive.

## Were the tasks easy to understand and did you enjoy solving them?
 While the tasks have been engaging and enjoyable to solve, I have found that some of them were more complex than others, requiring additional research and experimentation to fully understand. However, I appreciate the challenge provided by these tasks, as they have allowed me to expand my knowledge of Golem and its capabilities.

## How was your experience with a new Golem JS API?
In terms of the new Golem JS API, I have found it to be a bit challenging to work with at times. While I appreciate the improvements and enhancements made to the API, I think there is room for additional documentation and resources to help new users navigate the platform more easily. 

## Do you have any general feedback about Golem? Is there something we could improve from your perspective?

As for general feedback, I think Golem is a great platform, but there are a few areas where improvements could be made. Specifically, I think it would be beneficial to have more comprehensive and accessible documentation available, as well as more opportunities for community engagement and collaboration. Overall, I am grateful for the opportunity to participate in this program and look forward to continued involvement with Golem

## And that's it - thank you for your submission!

Our team will review and evaluate your feedback, then reward you with GLM reward for your future projects!

**Comment by tewodrosGirmaA** [comment]
![image](https://github.com/golemfactory/golem-js-preview-program/assets/118253010/8a9adfa0-f702-41b4-bf7e-1d50fd1fb098)

**Comment by tewodrosGirmaA** [comment]
I have shared the GitHub repository above, but it appears that it is not displayed as a clickable link. Here is the forked GitHub repository: https://github.com/tewodrosGirmaA/golem-js-preview-program

**Comment by VanDavv** [comment]
Hi @tewodrosGirmaA,

Thank you for your submission and patience! I reviewed your feedback and will verify the code as well, but could you describe what you meant by

> Additionally, issues is with network connectivity

Mentioned [here](https://github.com/tewodrosGirmaA/golem-js-preview-program/blob/master/tasks/3-parallel-file-conversion/FEEDBACK.md?plain=1#L102)

And could you also provide more context on the screenshot you've shared?

**Comment by tewodrosGirmaA** [comment]
Hi @VanDavv,

Thank you for your comment. To address your first question, the screenshot I shared in my previous comment was intended to show the error I encountered while trying to locate the environmental variable(YAGNA_APPKEY). As this was not directly related to the feedback, I included it in the comment section.

 Regarding network connectivity, I raised this issue in my feedback because Golem's providers are distributed globally, which can sometimes result in latency or connectivity issues that affect task performance. However, Golem offers a built-in retry mechanism that can help mitigate these issues. For example, you can use the following code to retry failed tasks up to three times:

const results = await Promise.all(
  tasks.map((task) =>
    executor.map(task.func, task.input, { retries: 3 })
  )
);

By carefully selecting and configuring the browser and utilizing Golem's retry mechanism, you can ensure that your image conversion task is executed successfully on the Golem network. ( I would like to clarify that my suggestion for further reference was a personal recommendation and not an official one. Additionally, I asked someone for their input and included it as an additional suggestion. I apologize for any confusion this may have caused)

**Comment by VanDavv** [comment]
Excellent, thanks for the clarification and additional context! I'll happily accept this submission now

**Comment by tewodrosGirmaA** [comment]
Thank you for your kind words and for accepting the submission.
