### ISSUE TITLE
[Submission] Golem JS Preview Program

### ISSUE THREAD

**Issue by Bam92** [golemfactory/golem-js-preview-program#8]
# Golem JS Preview Program Submission by Bam92

Thank you for your Golem JS Preview Program Submission!

Please make sure the feedback form in a Markdown file is filled for each of the tasks you’d like to submit!
Also, please make sure you've read the terms and conditions for this competition available here - 

## Legal Info

In order to receive the award, we need a minimum info about you for legal reasons:

- Email: news.abel@protonmail.com
- Country of origin: DRC

## Preferred reward currency

There are two currencies you can receive a reward in - USD and GLM. Since GLM is our cryptocurrency, we provide an additional **10% bonus to all rewards paid in GLMs!**.

Choose the preferred currency by checking (with `x`) one of the boxes below:

- [x] USD
- [ ] GLM (+10% bonus)

Please note that if you already have an accepted assignment from any of the freelance websites (e.g. fiverr.com, freelancer.com, upwork.com), you need to choose a reward in USD.

## Repository link
https://github.com/Bam92/golem-js-preview-program

## Submitted Tasks

Please check (with `x`) the boxes below with the tasks you'd like to submit:

- [ ] Text2Speech
- [x] Code Sandbox
- [ ] Parallel File Conversion
- [ ] Text2Speech Server
- [ ] Best Provider Selection

## How did you find out about Golem JS Preview Program? Please check (with `x`) the correct box below:

- [ ] fiverr.com 
- [ ] freelancer.com
- [x] upwork.com
- [ ] Digital Campaign (e.g. Reddit)
- [ ] Golem Network profiles
- [ ] Message on LinkedIn
- [ ] Other: [please answer here]

## How was your experience with Golem JS Preview Program so far?

It's quite well as it remembers old time Unix setup. You need to improve you DX.

## Were the tasks easy to understand and did you enjoy solving them?

No, not at all.

## How was your experience with a new Golem JS API?

I use APIs, but yours did help me. The doc is not that clear enough

## Do you have any general feedback about Golem? Is there something we could improve from your perspective?

See my feedback in the feedback file

## And that's it - thank you for your submission!

Our team will review and evaluate your feedback, then reward you with GLM reward for your future projects!

**Comment by VanDavv** [comment]
Hi @Bam92,

Thanks for your feedback. I see that you did have some issues, but neither feedback here nor the feedback in the feedback file indicates you actually tried to solve the issue, I also didn't see you reaching out on Discord.

We released an updated version of `gvmkit-build` last week, but I'm not sure which one you used.

Please reach out on Discord so that we can work together on these issues, I'm sure there's a lot of space for improvements, detecting those is a key of this initiative, and due to this reason I have to reject your feedback as of now.
