### ISSUE TITLE
[Submission] Golem JS Preview Program - Task 4

### ISSUE THREAD

**Issue by lightify97** [golemfactory/golem-js-preview-program#9]
# Golem JS Preview Program Submission by lightify97

Thank you for your Golem JS Preview Program Submission!

Please make sure the feedback form in a Markdown file is filled for each of the tasks you’d like to submit!
Also, please make sure you've read the terms and conditions for this competition available here - 

## Legal Info

In order to receive the award, we need a minimum info about you for legal reasons:

- Email: ramzanm461@gmail.com
- Country of origin: Pakistan

## Preferred reward currency

There are two currencies you can receive a reward in - USD and GLM. Since GLM is our cryptocurrency, we provide an additional **10% bonus to all rewards paid in GLMs!**.

Choose the preferred currency by checking (with `x`) one of the boxes below:

- [x] USD
- [ ] GLM (+10% bonus)

Please note that if you already have an accepted assignment from any of the freelance websites (e.g. fiverr.com, freelancer.com, upwork.com), you need to choose a reward in USD.

## Repository link
https://github.com/lightify97/golem-js-preview-program/tree/master/tasks/4-text-2-speech-server

The task code is added as a submodule in the task folder.
Original Repo: https://github.com/lightify97/golem-task-4

## Submitted Tasks

- [ ] Text2Speech
- [ ] Code Sandbox
- [ ] Parallel File Conversion
- [x] Text2Speech Server
- [ ] Best Provider Selection

## How did you find out about Golem JS Preview Program? Please check (with `x`) the correct box below:

- [ ] fiverr.com 
- [ ] freelancer.com
- [x] upwork.com
- [ ] Digital Campaign (e.g. Reddit)
- [ ] Golem Network profiles
- [ ] Message on LinkedIn
- [ ] Other: [please answer here]

## How was your experience with Golem JS Preview Program so far?

Very good and exciting. 

## Were the tasks easy to understand and did you enjoy solving them?
The task itself was easy but the documentation for the JS library is not helping at all.
I've mentioned about this in detail in the Feedback form.

## How was your experience with a new Golem JS API?
Very good. I learnt a lot of new things while working with Golem Network and JS api specifically.

## Do you have any general feedback about Golem? Is there something we could improve from your perspective?

Please improve the docs so everyone can build great products using Golem Network.

**Comment by VanDavv** [comment]
Hi @lightify97, thank you very much for your feedback! I'm going through it and I have one question:

You mention that you went through https://handbook.golem.network/ and you suggest a rewrite. We're actually in the middle of a migration to a new docs system that is hosted here - https://docs.golem.network/creators/javascript/

Is the organization of the new docs better? As I don't know to which extent the feedback applies to the old docs and to which to the new one. Happy to hear any suggestions 🙂

**Comment by lightify97** [comment]
Hey @VanDavv. Yeah I just went through the the new docs (https://docs.golem.network/creators/javascript/). These are better than previous ones. I assume this is a work in progress. As far as the general learning goes these docs are much better. But, I'll again emphasis the importance of good API documentation. That's what developers dig when faced with a new challenge or experiencing some issue. Hope the Docs team will take it into account. Again Thanks.
